// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClrCYuRj-kq1tVq3hOvX4TVlOjfdT2jgI',
    appId: '1:827326079916:web:cd1b6734107df5589a5009',
    messagingSenderId: '827326079916',
    projectId: 'agribioloop-6122b',
    authDomain: 'agribioloop-6122b.firebaseapp.com',
    storageBucket: 'agribioloop-6122b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHTRgass02KfpyWW3OZKYjUBlnMs8Fl2o',
    appId: '1:827326079916:android:a3487704f2691a889a5009',
    messagingSenderId: '827326079916',
    projectId: 'agribioloop-6122b',
    storageBucket: 'agribioloop-6122b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXdFK49OqLyjii_DLF29sOsZ5iZa_nXXc',
    appId: '1:827326079916:ios:a2bca6debbea55809a5009',
    messagingSenderId: '827326079916',
    projectId: 'agribioloop-6122b',
    storageBucket: 'agribioloop-6122b.firebasestorage.app',
    iosBundleId: 'com.example.agribioloop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXdFK49OqLyjii_DLF29sOsZ5iZa_nXXc',
    appId: '1:827326079916:ios:a2bca6debbea55809a5009',
    messagingSenderId: '827326079916',
    projectId: 'agribioloop-6122b',
    storageBucket: 'agribioloop-6122b.firebasestorage.app',
    iosBundleId: 'com.example.agribioloop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClrCYuRj-kq1tVq3hOvX4TVlOjfdT2jgI',
    appId: '1:827326079916:web:56d4a4259235a4b69a5009',
    messagingSenderId: '827326079916',
    projectId: 'agribioloop-6122b',
    authDomain: 'agribioloop-6122b.firebaseapp.com',
    storageBucket: 'agribioloop-6122b.firebasestorage.app',
  );

}